### PR TITLE
Add temperature and powerUsage per device

### LINKED ISSUE #9: request to add gpu temp sensor
Thanks

### PR DESCRIPTION
**Pull request by qcasey**
Hello, excellent integration! 

I agreed with #9, in that some device stats would be useful. This PR adds a sensor for each device's `temperature` and `powerUsage`. What are your thoughts on the feature? 

There's a small annoyance, where if the HA instance is set to Imperial units, the temerature is converted to `°F`  - do you know if it's possible to force `°C`?

Screenshot from 2021-03-25 16-00-27

Fixes #9

### CODE REVIEW

**Comment by RomRider** [comment]
That's great, thanks!

The conversion happens because of the device class I believe. The only way I see is to no set the device class for the temperature but then some people might still want the temperature in `°F` which in this case would require adding a setting in the integration config option.

**Comment by qcasey** [comment]
Hmm, even without device_class it still does the conversion. I'll need to revisit this later when I have time. Two notes to self:

1. [Workaround for displaying C without imperial conversion](https://community.home-assistant.io/t/configuration-template-how-to-convert-f-to-c-on-temperature/189003/32)
2. QuickMiner GPU/VRAM temperatures are [combined into one giant `number`](https://github.com/nicehash/NiceHashQuickMiner/issues/146)

**Comment by jdeath** [comment]
> Hmm, even without device_class it still does the conversion. I'll need to revisit this later when I have time. Two notes to self:
> 
> 1. [Workaround for displaying C without imperial conversion](https://community.home-assistant.io/t/configuration-template-how-to-convert-f-to-c-on-temperature/189003/32)

I hack I did was change the temperature setup line in sensor.py to:
{"temperature": {"numerical": True, "unit": "C"}},  
Don't use °C, or it will figure it out and still convert it to F. I also use F, but prefer C for GPU temp. I also added the below lines to get Fan and load sensors:
{"revolutionsPerMinutePercentage": {"unit": PERCENTAGE}},
{"load": {"unit": PERCENTAGE}}

My device stats stop updating after a while, not sure why. I manual refresh or core-restart brings them back.

**Comment by qcasey** [comment]
I sold off my cards, so unfortunately I won't be able to contribute more here as I can't test my work.

**Comment by RomRider** [comment]
This is superseded by #18, I'm going to close that.

**Pull request closed without merging**
